In [2]:
import numpy as np

In [3]:
import numpy
numpy.__version__

'1.26.4'

In [4]:
a=np.zeros((2,2))
print(a)

b=np.ones((1,2))
print(b)

c=np.full((2,2),7)
print(c)

d=np.eye(2)
print(d)

e=np.random.random((2,3))
print(e)



[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.29978539 0.44037876 0.69697267]
 [0.83050167 0.60290711 0.84047939]]


In [5]:
arr=np.array([2,2,3,4,5,6])
print(arr)

[2 2 3 4 5 6]


In [6]:
arr=np.array([2,3,4,5,6,7])
print(arr[5]+arr[0])

9


In [7]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[0,0,0])
print(arr[0,0,1])
print(arr[0,0,2])
print(arr[0,1,0])
print(arr[0,1,1])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,0,1])
print(arr[1,0,2])
print(arr[1,1,0])
print(arr[1,1,1])
print(arr[1,1,2])


1
2
3
4
5
6
7
8
9
10
11
12


In [8]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[-1:-4:-1])

[2 3 4]
[7 6 5]


In [9]:
arr=np.array([1.1,2.1,3.1])
newarr=arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [10]:
import numpy as np
a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [12]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [13]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [14]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [16]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 0])

4


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-4:-7:-1])

[4 3 2]


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-1::-2])

[7 5 3 1]


In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [20]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [22]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [23]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [24]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [25]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [26]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [29]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [32]:
from numpy import random
x = random.rand()

print(x)

0.5517695240560565


In [33]:
x=random.randint(100, size=(5))

print(x)

[52 22 89 57 98]


In [36]:
x = random.randint(100, size=(3, 5))

print(x)

[[77 17 35 72  7]
 [90 27 16 86 68]
 [76 34 80 86  7]]


In [37]:
x = random.randint(100, size=(3, 5))

print(x)

[[54 25 95 78 80]
 [52 20 85 87 96]
 [74 97 59 45 87]]


In [38]:
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 9 7 5 3]
 [7 7 5 5 7]
 [5 5 5 5 7]]


In [40]:
x = random.choice([3, 5, 7, 9])

print(x)

5
